### ISSUE TITLE
Exact Dob format need in  "Add employee"

### ISSUE THREAD

**Issue by SkPratihar1** [prosenjit-manna/node-express-leave-management#3]
"ORG_OWNER" login the application-->Call add employee API  (http://localhost:4000/employee/add) --> In Api Body 
{
    "userId": "661524db8b7fb5bd964db712",
    "name": "Prince Employee",
    "phone": "9212",
    "gender": "M",
    "dob": "23/12"
}
Dob is not formated mm/dd/yy.

**Comment by prosenjit-manna** [comment]
This is has been fixed
