### ISSUE TITLE
Getting 404 when deleting any employee

### ISSUE THREAD

**Issue by Jiniya-Manna** [prosenjit-manna/node-express-leave-management#7]
**Actual scenario:**

When sending the delete request to delete an employee, getting a '404 not found' response.

Here is the response:

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Error</title>
</head>

<body>
    <pre>Cannot DELETE /employee/delete</pre>
</body>

</html>

**Expected scenario:**
The employee would be deleted successfully.

**Comment by prosenjit-manna** [comment]
method has been changed
