### ISSUE TITLE
Date validation is needed in "add laave"

### ISSUE THREAD

**Issue by SkPratihar1** [prosenjit-manna/node-express-leave-management#8]
Actual scenario:
"ORG_OWNER" login to the application --> Call leave add API (  {{base_api_endpoint}}/leave/add) -->
Start date select the future date and end date select the previous date.
End date should not less than start date
<img width="1736" alt="Screenshot 2024-04-16 at 1 59 05 PM" src="https://github.com/prosenjit-manna/node-express-leave-management/assets/107917285/9ca10e4c-e9bd-4f31-8e5f-c6ac286c170f">
{
    "userId": "661e281c58fb7da48ae31837",
    "leaveStart": "2024-04-18T13:32:32.608Z",
    "leaveEnd": "2024-04-16T18:32:32.608Z",
    "count": 1,
    "leaveType": "CL"
}

**Comment by prosenjit-manna** [comment]
this is intentional, can be added
