### ISSUE TITLE
Employee Old data is displayed after editing employe details

### ISSUE THREAD

**Issue by SkPratihar1** [prosenjit-manna/node-express-leave-management#9]
Actual Scenario:
"ORG_OWNER" add employee add employee  ({{base_api_endpoint}}/employee/add) --> Employee edit using employee id ({{base_api_endpoint}}/employee/edit) -->   View employee using old employee id ( {{base_api_endpoint}}/employee/view)-->
Old employee data is displayed but employee details are already edited.
After editing the employee, the employee ID is changed so when viewing the employee using the old employee ID

**Comment by prosenjit-manna** [comment]
Fixed
